package model.workspace;

public enum WorkspaceAction
{
	COLLECT_FILE_METADATA,
	LOAD_RAW_DATA, LOAD_DISTANCES, LOAD_MDS_COORDINATES,
	CALCULATE_DISTANCES, CALCULATE_MDS_COORDINATES,
	RESET,
	ALL, NONE
}
