package view.components;

public enum VisualizationComponentType
{
	NUMERICAL_HEATMAP,
	CATEGORICAL_HEATMAP,
	GLOBAL_SCATTERCHART,
	PARAMSPACE_SCATTERCHART, 
	SCENTED_FILTER,
	DISTANCES_BARCHART,
	PARALLEL_TAG_CLOUD,
	SETTINGS_PANEL
}
